import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import SingleFeature from "@/src/components/SingleFeature/SingleFeature";
import Registration from "@/src/components/PatientRegistration/PatientRegistration";
import { Toaster } from "react-hot-toast";
// import { useRouter } from "next/router";

const inter = Inter({ subsets: ["latin"] });

export default function SingleFeaturePage() {
  return (
    <>
      <Head>
        <title>Single Feature</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className="container">
          <SingleFeature />
          <Registration />
        </div>
          {/* Toast Notifications */}
      <Toaster position="top-right" reverseOrder={false} />
      </main>
    </>
  );
}
